#!/bin/bash
#
# Copyright (C) 2023 Jonathan Sanfilippo <jonathansanfilippo.uk@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.



echo "This script will clear your home cache and trash. To continue? [y/N]"
read answer

if [ "$answer" == "y" ]; then
  echo "Cleaning..."

  # Pulizia cache home
  rm -rf ~/.cache/*

  # Pulizia cestino
  rm -rf ~/.local/share/Trash/*

  echo ""
  echo ""
  read -p " Cleaning completed. Press [Enter] key to esc"
  echo ""
  echo ""
else
  read -p  "Cleaning aborted.  Press [Enter] key to esc"
fi
