#!/bin/sh
#
# Copyright (C) 2023 Jonathan Sanfilippo <jonathansanfilippo.uk@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# URL
verified="$HOME/.config/archmain/scripts/verified"
urltemp="$HOME/.config/archmain/data/temp.json"
ignore=$(cat "$HOME/.config/archmain/data/ignore.json")
ign="$HOME/.config/archmain/data/ignore.json"


#temp.json
echo "Last updates installed --------------- $(date '+%a %d %b, %H:%M')" > "$urltemp"
echo "" >> "$urltemp"
echo "$(checkupdates 2>/dev/null)"  >> "$urltemp"
echo "$(pikaur -Qua | cut -c 2-)" >> "$urltemp"

#check if ignore and update
if [ -s "$ign" ]
then
    sudo pikaur -Syu --ignore "$ignore"
else
    sudo pikaur -Syu 
fi


#go to verified
echo ""
echo ""
read -p "Press [Enter] key to save list updates.."
echo ""
echo ""
$verified

