#!/bin/sh
#
# Copyright (C) 2023 Jonathan Sanfilippo <jonathansanfilippo.uk@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# URL

list="$HOME/.config/archmain/data/list-upds"
urltemp="$HOME/.config/archmain/data/temp"
last="$HOME/.config/archmain/data/last"

# Variabili cmd

get_updates(){
    AUR=$(pikaur -Qqua)
    ListUpdates=$(checkupdates 2>/dev/null)
    Pending=$(expr $(pikaur -Qqua | wc -l) + $(checkupdates 2>/dev/null | wc -l))
}

get_updates
    if [ "$Pending" -eq 1 ]; then
        echo "$Pending Update" > "$list"
        echo " " >> "$list"
        echo "$ListUpdates" >> "$list"
        echo "$AUR" >> "$list"

    elif [ "$Pending" -ge 1 ]; then
        echo "$Pending Updates" > "$list"
        echo " " >> "$list"
         echo "$ListUpdates" >> "$list"
        echo "$AUR" >> "$list"

    else
        echo "System Updated" > "$list"
    fi

cp "$urltemp" "$last"

